### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by xush6528** [hust-latex/husttrans#1]
学长您好，
我是11级许世豪，在黑老师这做毕设

用你的模板的时候出现问题向你请教

windows下，装的texlive
字体安装了
模板安装这样应该是成功了吧。

但是这么简单几行也不能编译过

![1](https://cloud.githubusercontent.com/assets/7608630/6505870/50082250-c381-11e4-9f52-2826da7d1902.png)
![2](https://cloud.githubusercontent.com/assets/7608630/6505884/66727338-c381-11e4-88fd-d45dd170b3df.png)
![qq 20150305212830](https://cloud.githubusercontent.com/assets/7608630/6505887/6a883ba6-c381-11e4-8c9f-fda096e2fbaa.png)

**Comment by xu-cheng** [comment]
http://hust-latex.github.io/faqs/

**Comment by xiaojun-hei** [comment]
Thanks a lot. Cheers
