### ISSUE TITLE
husttrans.cls Missing \begin{document}

### ISSUE THREAD

**Issue by QYQSDTC** [hust-latex/husttrans#3]
After I installed the required fonts there is another problem and I think it's hard for me to solve.
<img width="888" alt="2017-01-26 11 59 27" src="https://cloud.githubusercontent.com/assets/15608306/22319585/197726b8-e3bf-11e6-8ecb-dac0345a9c0d.png">

**Comment by xu-cheng** [comment]
Please update the template. I think you are using an outdated version.
